const env = {
	AUTH_SECRET: process.env.NEXT_PUBLIC_AUTH_SECRET,

	ENV: process.env.NEXT_PUBLIC_ENV,

	APPLE_ID: process.env.NEXT_PUBLIC_APPLE_ID,

	ECOM_BRAND_ID: process.env.NEXT_PUBLIC_ECOM_BRANCH_ID,

	ENABLE_MUSIC_PLAYER: process.env.NEXT_PUBLIC_ENABLE_MUSIC_PLAYER,
	ENABLE_GYM_HOLD_REGISTRATION: process.env.NEXT_PUBLIC_ENABLE_GYM_HOLD_REGISTRATION,
	ENABLE_GYM_REGISTRATION: process.env.NEXT_PUBLIC_ENABLE_GYM_REGISTRATION,
	ENABLE_CHAT: process.env.NEXT_PUBLIC_ENABLE_CHAT,
	ENABLE_GYM: process.env.NEXT_PUBLIC_ENABLE_GYM,

	BASE_AUTH_URL: process.env.NEXT_PUBLIC_BASE_AUTH_URL,
	BASE_API_URL: process.env.NEXT_PUBLIC_BASE_API_URL,
	ECOM_BASE_URL: process.env.NEXT_PUBLIC_ECOM_BASE_URL,
	GUEST_ECOM_BASE_URL: process.env.NEXT_PUBLIC_GUEST_ECOM_BASE_URL,
	GUEST_SOCIAL_API_URL: process.env.NEXT_PUBLIC_GUEST_SOCIAL_API_URL,
	GYM_BASE_URL: process.env.NEXT_PUBLIC_GYM_BASE_URL,

	AWS_ACCESS_KEY_ID: process.env.NEXT_PUBLIC_AWS_ACCESS_KEY_ID,
	AWS_SECRET_ACCESS_KEY: process.env.NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY,
	AWS_DEFAULT_REGION: process.env.NEXT_PUBLIC_AWS_DEFAULT_REGION,
	AWS_BUCKET: process.env.NEXT_PUBLIC_AWS_BUCKET,
	AWS_ENDPOINT: process.env.NEXT_PUBLIC_AWS_ENDPOINT,

	FB_NOTI_APP_ID: process.env.NEXT_PUBLIC_FB_NOTI_APP_ID,
	FB_NOTI_MEASUREMENT_ID: process.env.NEXT_PUBLIC_FB_NOTI_MEASUREMENT_ID,

	FB_CRE_PRIVATE_KEY_ID: process.env.NEXT_PUBLIC_FB_CRE_PRIVATE_KEY_ID,
	FB_CRE_PRIVATE_KEY: process.env.NEXT_PUBLIC_FB_CRE_PRIVATE_KEY,
	FB_GOOGLE_MAP_API_KEY: process.env.NEXT_PUBLIC_FB_GOOGLE_MAP_API_KEY,

	GOOGLE_SIGN_IN_WEB_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_SIGN_IN_WEB_CLIENT_ID,
	GOOGLE_SIGN_IN_IOS_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_SIGN_IN_IOS_CLIENT_ID,
};

export { env };
